("cashier_interface", "واجهة الكاشير"),
("products_management", "إدارة المنتجات"),
("inventory_management", "إدارة المخزون"),
("reports_view", "رؤية التقارير"),
("customers_management", "إدارة العملاء"),
("users_management", "إدارة المستخدمين"),
("invoices_management", "إدارة الفواتير"),
("settings_edit", "تعديل الإعدادات"),
("suppliers_management", "إدارة الموردين"),
("purchase_invoices", "إنشاء فواتير الشراء"),
("stock_movements_view", "رؤية حركة المخزون"),
